services:
    web:
        build: 
            dockerfile: Dockerfile
        ports:
            - "96:80"
        volumes:
            - ./app:/var/www/html
        depends_on:
            - db
    
    db:
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - db_data:/var/lib/mysql
    
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - "8181:80"
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        depends_on:
            - db
         
volumes:
    db_data: 